### PR TITLE
Add employment_position term synonyms

### PR DESCRIPTION
**Pull request by chriswoodrich**

### CODE REVIEW

**Comment by chriswoodrich** [comment]
@sarkis Can I get a QA here?

**Comment by sarkis** [comment]
Looks good to me :+1:

What is the timeline on getting the entire story QA'd and into production?

**Comment by chriswoodrich** [comment]
The feature that uses this has been QA'd and is in production (as of Friday).  Currently it's an admin-only feature, so no rush on this piece.

**Comment by chriswoodrich** [comment]
@sarkis, so is it as simple as merging and deploying?

**Comment by sarkis** [comment]
@chriswoodrich as discussed in slack, we will need to do a separate deploy of the synonyms to elasticsearch and rolling restart the cluster. I will find a good low traffic time to do this, this week, and post the date/time of the maintenance here.

**Pull request merged**
